name: "PR commit summary"
description: "Github action that summarizes the PR commits and posts it to notion."
inputs:
  ghToken:
    description: "Github token"
    required: true
  openAiKey:
    description: "Open AI API key.If empty it will be ignored."
    required: false
  openAiOrg:
    description: "Open AI org id."
    required: false
  anthropicKey:
    description: "Anthropic API key. If empty it will be ignored."
    required: false
  linearKey:
    description: "Linear API key. If empty it will be ignored."
    required: false
  linearViewId:
    description: "Linear View Id."
    required: false
  notionKey:
    description: "Notion API key."
    required: false
  notionDbId:
    description: "Notion Database ID."
    required: false
  prompt:
    description: "Summary prompt"
    required: false
    default: "Provide a detailed summary of the following commit messages in markdown format:"
  changelog:
    description: "Link to the changelog"
    required: false
  version:
    description: "Release version"
    required: false

branding:
  icon: box
  color: red

runs:
  using: "composite"
  steps:
    - name: 📄 Get PR commit messages
      shell: bash
      run: |
        git log origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s" > commit_messages.txt

    - name: 💿 Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12" # install the python version needed

    - name: 🦺 Install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🤖 Run
      id: summary
      run: |
        export COMMITS=$(cat commit_messages.txt)
        python src/main.py
      shell: bash
      env:
        OPENAI_KEY: ${{ inputs.openAiKey }}
        OPENAI_ORG: ${{ inputs.openAiOrg }}
        ANTHROPIC_KEY: ${{ inputs.anthropicKey }}
        NOTION_KEY: ${{ inputs.notionKey }}
        LINEAR_KEY: ${{ inputs.linearKey }}
        LINEAR_VIEW_ID: ${{ inputs.linearViewId }}
        NOTION_DB_ID: ${{ inputs.notionDbId }}
        CHANGELOG: ${{ inputs.changelog }}
        VERSION: ${{ inputs.version }}
        PROMPT: ${{ inputs.prompt }}

    - name: 🖨️ Print result
      shell: bash
      run: echo ${{ steps.summary.outputs.summary }}
